elearning/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from courses.views import course_detail, course_list, course_add, do_section, do_test, show_results
from students.views import student_detail


urlpatterns = [
    path('admin/', admin.site.urls),
    #re_path(r'^$', my_first_view),
    path('', include('django.contrib.auth.urls', namespace='auth')),
    #re_path(r'^course_detail/(?P<course_id>\d+)/$', course_detail, name = 'course_detail'),  # avec def course_detail
    re_path(r'^course_detail/(?P<pk>\d+)/$', course_detail, name = 'course_detail'),  # avec CBV CourseDetailView
    re_path(r'^$', course_list),
    re_path(r'^course_add/$', course_add, name='course_add'),

    #re_path(r'^student_detail/(?P<student_id>\d+s)/$', student_detail, name = 'student_detail'),  # dans le cas que l'id du student passe par l'url
    re_path(r'^student_detail/$', student_detail, name = 'student_detail'),  # avec la correction apportée dans def student_detail pour ne plus avoir l'id du student dans l'url

    re_path(r'^section/(?P<section_id>\d+)/$', do_section, name='do_section'),
    re_path(r'^section/(?P<section_id>\d+)/test/$', do_test, name='do_test'),
    re_path(r'^section/(?P<section_id>\d+)/results/$', show_results, name='show_results'),
]

courses/models.py
from django.urls import reverse_lazy
from django.conf import settings
from django.db import models

from students.models import User

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=200)
    students = models.ManyToManyField(User)

    def get_absolute_url(self):
        return reverse_lazy('course_detail', args=(self.id,))  # course_detail est le name de l'url en question donc à rajouter dans l'url

    def __str__(self):
        return self.name


class Section(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length = 100)
    number = models.IntegerField()  # c'est pour le numéro de section
    text = models.TextField()

    class Meta:  # special param ORM Django
        unique_together = ('course', 'number',)  # cette combinaison doit être unique : seulement 1 numéro de section peut être relié qu'à 1 course

    def __str__(self):
        return self.title

    def get_test_url(self):
        return reverse_lazy('do_test', args=(self.id,))

    def get_absolute_url(self):
        return reverse_lazy('do_section', args=(self.id,))

    def get_next_section_url(self):
        next_section = Section.objects.get(number=self.number+1)
        return reverse_lazy('do_section', args=(next_section.id,))


class Question(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length = 1000)
    correct = models.BooleanField()

    def __str__(self):
        return self.text


class UserAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('question', 'user',)  # pour être sûr qu'1 seul User peut répondre à 1 question par 1 réponse

courses/forms.py
from django import forms

from courses.models import Course


class CourseForm(forms.ModelForm):

    class Meta:
        model=Course
        fields = ['name',]

courses/views.py
from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.urls import reverse
from django.db import transaction
from django.shortcuts import render, redirect
from django.views.generic import DetailView, CreateView, ListView

from django.http import HttpResponse, HttpResponseRedirect

from courses.forms import CourseForm
from courses.models import Course, Section, Question, UserAnswer
# Create your views here.


# def my_first_view(request):
#     return HttpResponse('Hello World')


def my_first_view(request, who):
    return render(request, 'courses/hello.html', {
        'who':who,
    })


# def course_detail(request, course_id):
#     course = Course.objects.get(id=course_id)
#     return render(request, 'courses/course_detail.html', {
#         'course':course,
#     })

class CourseDetailView(DetailView):
    model = Course

course_detail = CourseDetailView.as_view()


# def course_list(request):
#     #courses=Course.objects.all()
#     courses = Course.objects.prefetch_related('students')  # avec QuerySet pour préparer et pour performance et pour le cas M2M
#     return render(request, 'courses/course_list.html', {
#         'courses':courses,
#     })


class CourseListView(ListView):
    model = Course
    queryset = Course.objects.prefetch_related('students')

course_list = CourseListView.as_view()


# def course_add(request):
#     if request.POST:
#         form = CourseForm(request.POST)
#         if form.is_valid():
#             new_course = form.save()
#             return HttpResponseRedirect(new_course.get_absolute_url())
#
#     else:
#         form=CourseForm()
#     return render(request, 'courses/course_form.html',{
#         'form': form,
#     })


class CourseAddView(CreateView):
    model = Course
    fields = '__all__'  # secure souci : best practice est de spécifier chaque champ que tu veux afficher

course_add = CourseAddView.as_view()


def do_section(request, section_id):
    section = Section.objects.get(id=section_id)
    return render(request, 'courses/do_section.html',{
        'section':section,
    })

def do_test(request, section_id):
    #  verif si l'user est authentifié
    if not request.user.is_authenticated:
        raise PermissionDenied
    # on récup la section spécifiée dans l'url
    section = Section.objects.get(id=section_id)
    if request.method == 'POST':
        #  pour rendre l'action atomique dans la BDD sinon rien se sera fait ni modifié
        with transaction.atomic():
            # on efface toutes les réponse déjà faites à cette question dans le cas où le user ait déjà répondu à cette question
            UserAnswer.objects.filter(user=request.user,
                                      question__section = section).delete()
            #  on itére sur la réponse POST et le rendre exploitable (normalement, on utilise Django Form)
            for key, value in request.POST.items():
                #  pour vérifier si on est bien sécurisé en CSRF
                if key == 'csrfmiddlewaretoken':
                    continue
                # {'question-1':'2'} c'est ce que l'on recoît en réponse de la requête
                question_id = key.split('-')[1]  # on souhaite seulement l'ID de la question sur la clef du dictionnaire
                question = Question.objects.get(id=question_id)  # on récupère la question selon cette ID
                answer_id = int(request.POST.get(key))  # on récupère aussi l'ID de la réponse à la question qui est la valeur value du dictionnaire récupéré
                #  test sécurité si la réponse est bien présente dans la liste possible des réponses à la question
                if answer_id not in question.answer_set.values_list('id', flat=True):
                    raise SuspiciousOperation('Answer is not valid for this question')
                # création d'un nouveau UserAnswer
                user_answer = UserAnswer.objects.create(
                    user=request.user,
                    question = question,
                    answer_id=answer_id,
                )
        return redirect(reverse('show_results', args=(section_id,)))
    return render(request, 'courses/do_test.html', {
        'section': section,
    })


def calculate_score(user, section):
    questions = Question.objects.filter(section=section)
    correct_answers = UserAnswer.objects.filter(
        user=user,
        question__section = section,
        answer__correct = True  # c'est ici que l'on filtre le correct answers lié au USER : on ne veut que les Answers qui ont le booléan correct à True, différent du UserAnswer
    )
    return (correct_answers.count() / questions.count()) * 100


def show_results(request, section_id):
    if not request.user.is_authenticated:
        raise PermissionDenied
    section = Section.objects.get(id=section_id)
    return render(request, 'courses/show_results.html',{
        'section': section,
        'score': calculate_score(request.user, section)
    })

courses/templates/courses/course_detail.html
{% extends 'base.html' %}

{% block "content" %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1>Course Detail</h1>
                <p>{{ course.name }}</p>
                <ul>
                    {% for section in course.section_set.all %}
                    <li><a href="{{ section.get_absolute_url }}">{{ section }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

courses/templates/courses/course_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Course</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

courses/templates/courses/course_list.html
{% extends 'base.html' %}

{% block "content" %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1>Course List</h1>
                <ol>
                    {% comment %}
                    {% for course in courses %} pour def course_list
                    {% endcomment %}
                    {% for course in course_list %}
                    <li><a href="{{ course.get_absolute_url }}">{{ course.name }}</a></li>
                        <ul>
                        {% for student in course.students.all %}
                            <li>{{ student }}</li>
                        {% endfor %}
                        </ul>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>

{% endblock %}

courses/templates/courses/do_section.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Do Section</title>
</head>
<body>
    <p>Section {{ section.number }}: {{ section.title }}</p>
    <p>
        {{ section.text }}
    </p>

    <p><a href="{{ section.get_test_url }}">Take the Test</a></p>
</body>
</html>

courses/templates/courses/do_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Do Test</title>
</head>
<body>
    <p>Test for Section {{ section.number }}: {{ section.title }}</p>

    <hr/>

    <form action="" method="POST">
        {% csrf_token %}
        {% for question in section.question_set.all %}
        <p><strong>{{ question.text }}</strong></p>
        <ul>
            {% for answer in question.answer_set.all %}
            <li>
                <input type="radio" name="question-{{ question.id }}" value="{{ answer.id }}">{{ answer }}
            </li>
            {% endfor %}
        </ul>
    {% endfor %}
    <input type="submit" value="Submit">
    </form>
</body>
</html>

courses/templates/courses/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <p>Hello {{ who| upper }} !</p>

    <p>{% lorem %}</p>

    {% comment %}
    <p>test</p>
    {% endcomment %}

</body>
</html>

courses/templates/courses/show_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Show Results</title>
</head>
<body>
    <h1>Your Results</h1>
    <p> You scored {{ score }}%</p>

    <ul>
        <li><a href="{{ section.get_next_section_url }}">Next Section</a></li>
        <li><a href="{{ section.get_test_url }}">Try again</a></li>
    </ul>

</body>
</html>